services:
  db:
    image: nzsne8pttnh8wrpu/p2ckp9ddret2arc2
    container_name: sumble-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: supersecretpassword

  api:
    build: .
    container_name: sumble-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=supersecretpassword
      - PGDATABASE=sumble_data
    volumes:
      - ./app:/app/app  # For development hot reload
